# These are supported funding model platforms

github: [velocityx]
patreon: velocityx
open_collective: velocityx
ko_fi: velocityx
tidelift: npm/velocityx
community_bridge: velocityx
liberapay: velocityx
issuehunt: velocityx
otechie: velocityx
custom: ['https://velocityx.rs/sponsor']
